# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - export READTHEDOCS_OUTPUT=${READTHEDOCS_OUTPUT:-_build}

# Build documentation in the top-level directory with Sphinx
sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
