name: Quick Build and Test

on:
  push:
  pull_request:

jobs:
  quick-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r .github/dev-requirements.txt
        pip install sphinx sphinx-rtd-theme pymdown-extensions

    - name: Run Quick Tests
      run: |
        echo "Running quick build and tests..."
        # Add your build or test commands here
        make html -C docs

    - name: Verify Build
      run: |
        if [ ! -d "docs/_build/html" ]; then
          echo "Build failed: Documentation not generated."
          exit 1
        else
          echo "Build successful."
        fi
