name: ovis-docs build and check
on: pull_request
jobs:
  spell-and-linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: >-
          sudo apt-get update -y &&
          sudo apt-get install -y python3-pip &&
          sudo pip3 install --upgrade -r ./requirements.txt

    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: "*.rst */*.rst */*/*.rst"
   
    - name: make linkcheck
      run: make linkcheck

    - name: Check Sphinx documentation
      run: sphinx-build -n -b html . _build/html
